import ErrorBase from '@/lib/ErrorBase';

export type BookReviewErrorName =
  | 'IMAGE_UPLOAD_ERROR'
  | 'GET_CATEGORIES_ERROR'
  | 'PUBLISH_ERROR'
  | 'UPDATE_ERROR'
  | 'GET_BOOKREIVEW_LIST_ERROR'
  | 'GET_BOOKREVIEW_ERROR'
  | 'GET_ALL_BOOKREVIEW_ID_ERROR'
  | 'GET_DRAFT_SAVED_LIST_ERROR'
  | 'GET_PAGING_BOOKREVIEW_LIST_ERROR'
  | 'GET_PAGING_BOOKREVIEW_LIST_BY_TAG_ERROR'
  | 'GET_PAGING_BOOKREVIEW_LIST_BY_CATEGORY_ERROR'
  | 'GET_PAGING_FOLLOWING_BOOKREVIEW_LIST_ERROR'
  | 'GET_MOST_LIKED_BOOKREVIEW_LIST_ERROR'
  | 'GET_FOLLOWING_BOOKREVIEW_LIST_ERROR'
  | 'DELETE_BOOKREVIEW_ERROR'
  | 'LIKE_ERROR'
  | 'UNLIKE_ERROR'
  | 'CHECK_IS_LIKE_ERROR';

export class BookReviewError extends ErrorBase<BookReviewErrorName> {}
